FROM webhippie/minecraft-vanilla:1.12.2-arm64@sha256:34e1afed43a45219b0e4b38e9975ab75cbd36c9b2b0f65be5c04d1b9d5636f37

VOLUME ["/var/lib/minecraft", "/etc/minecraft/override"]
EXPOSE 25565 25575 8123

ENV MINECRAFT_LEVEL_TYPE BIOMESOP

ENV FORGE_VERSION 14.23.5.2847
ENV FORGE_JAR forge-${MINECRAFT_VERSION}-${FORGE_VERSION}.jar
ENV FORGE_URL https://maven.minecraftforge.net/net/minecraftforge/forge/${MINECRAFT_VERSION}-${FORGE_VERSION}/forge-${MINECRAFT_VERSION}-${FORGE_VERSION}-installer.jar
ENV DYNMAP_JAR Dynmap-3.3.2-forge-1.12.2.jar
ENV DYNMAP_URL https://media.forgecdn.net/files/3637/283/${DYNMAP_JAR}

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y libatomic1 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  curl --create-dirs -sLo /usr/share/minecraft/forge-${MINECRAFT_VERSION}-${FORGE_VERSION}-installer.jar ${FORGE_URL} && \
  cd /usr/share/minecraft && \
  mkdir mods && \
  java -jar forge-${MINECRAFT_VERSION}-${FORGE_VERSION}-installer.jar --installServer && \
  rm -f forge-${MINECRAFT_VERSION}-${FORGE_VERSION}-installer.jar forge-${MINECRAFT_VERSION}-${FORGE_VERSION}-installer.jar.log && \
  curl --create-dirs -sLo /usr/share/minecraft/mods/${DYNMAP_JAR} ${DYNMAP_URL}

COPY ./overlay /
COPY ./client/overrides /usr/share/minecraft
COPY ./client/manifest.json /usr/share/minecraft
COPY ./client/modlist.html /usr/share/minecraft
