FROM webhippie/minecraft-forge:14.23.5-amd64@sha256:67f43503f1d50a65864d3608099753b393725c6d8af66cf7b9a71da33a85865f

VOLUME ["/var/lib/minecraft", "/etc/minecraft/override"]
EXPOSE 25565 25575 8123

ENV MINECRAFT_LEVEL_TYPE BIOMESOP

RUN apk update && \
  apk upgrade && \
  apk add --no-cache jq && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
COPY ./client/overrides /usr/share/minecraft
COPY ./client/manifest.json /usr/share/minecraft
COPY ./client/modlist.html /usr/share/minecraft

RUN download-mods
