FROM webhippie/minecraft-forge:14.23.5-amd64@sha256:67f43503f1d50a65864d3608099753b393725c6d8af66cf7b9a71da33a85865f

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Minecraft ownTech" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 25565 25575 8123
VOLUME ["/var/lib/minecraft", "/etc/minecraft/override"]

WORKDIR /var/lib/minecraft
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

ENV MINECRAFT_LEVEL_TYPE BIOMESOP

COPY ./overlay  /
