FROM webhippie/minecraft-forge:14.23.5-arm64v8@sha256:82aaa249907261d8e82fad3aa6a547a38a78553f5687acebe30ac198ac9fea9b

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Minecraft ownTech" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 25565 25575 8123
VOLUME ["/var/lib/minecraft", "/etc/minecraft/override"]

WORKDIR /var/lib/minecraft
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

ENV MINECRAFT_LEVEL_TYPE BIOMESOP

COPY ./overlay  /
