#!/usr/bin/env bash

declare -x MINECRAFT_MODS_DIR
[[ -z "${MINECRAFT_MODS_DIR}" ]] && MINECRAFT_MODS_DIR="${MINECRAFT_GAME_DIR}/mods"

declare -x MINECRAFT_BACKUPS_DIR
[[ -z "${MINECRAFT_BACKUPS_DIR}" ]] && MINECRAFT_BACKUPS_DIR="${MINECRAFT_DATA_DIR}/backups"
