---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: minecraft-server
    options:
      labels:
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/component: server
    literals:
      - MINECRAFT_MOTD=ownTech by Webhippie

secretGenerator:
  - name: minecraft-server
    options:
      labels:
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/component: server
    literals: []

images:
  - name: minecraft-server
    newName: quay.io/crafthippie/owntech
    newTag: 3.3.1@sha256:4c939b0b46205d6f40c69517199ab789e476755f85491b4937e422bd87550ef1

...
