---
name: changes

"on":
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Build changelog
        uses: actionhippie/calens@v1
        with:
          target: CHANGELOG.md

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Crafthippie
          author_email: crafthippie@webhippie.de
          add: CHANGELOG.md
          message: "docs: automated changelog update"
          push: true
          commit: --signoff

...
